version: "3"
services:
  api:
    container_name: api
    build: 
      context: ./server
      dockerfile: node.dockerfile
    ports: 
      - "4000:4000"
    restart: unless-stopped
    volumes:
      # This is needed to run nodemon through the container
      - ./server:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    networks:
      - mern-app
  react_frontend:
    container_name: react_frontend
    stdin_open: true
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports: 
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - mern-app
  # web-server:
  #   container_name: web-server
  #   build: 
  #     context: ./dockerfiles/nginx
  #     dockerfile: web-server.dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./dockerfiles/nginx/default.conf:/etc/nginx/default.conf
  #   depends_on:
  #     - api
  #     - react_frontend

networks:
  mern-app:
    driver: bridge
