version: "3"
services:
  api:
    container_name: api
    build: 
      context: ./server
      dockerfile: node.dockerfile
    ports: 
      - "4000:4000"
    volumes:
      # This is needed to run nodemon through the container
      - ./server:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    networks:
      - mern-app
  react_frontend:
    container_name: react_frontend
    stdin_open: true
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
